---
apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: gowthamanprojects-dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: microservice
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: microservice
  namespace: gowthamanprojects-dev
spec:
  to:
    kind: Service
    name: microservice
  port:
    targetPort: 8080
  wildcardPolicy: None